import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Loader2, Wand2, RefreshCw, Sliders } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { normalizeTables, checkConsistency } from '@/lib/matchBackfiller';
import { toast } from "sonner";

/**
 * Generates (and regenerates) realistic league table stats via LLM, then
 * normalizes them so W+D+L=played, sum(W)=sum(L), and sum(GF)=sum(GA) —
 * which is what the deterministic backfiller needs to reproduce the table exactly.
 *
 * Match results themselves are generated by <BackfillMatchesButton />, which
 * guarantees a match to the table (the LLM match generator did NOT, so it was removed).
 */
export default function AIStatsGenerator({ tableRows, setTableRows, seasonData, league, divisionTeamCount, seasonId, leagueId }) {
    const [loading, setLoading] = useState(false);

    const numTeams = tableRows.filter(r => r.club_name).length;
    const teamsInDivision = divisionTeamCount || numTeams;
    const gamesPerTeam = (teamsInDivision - 1) * 2;
    const hasStats = tableRows.some(r => (r.won || 0) > 0 || (r.drawn || 0) > 0 || (r.lost || 0) > 0);

    const normalizeExisting = async () => {
        if (numTeams < 2) return;
        setLoading(true);
        try {
            const validRows = tableRows.filter(r => r.club_name && r.club_id);
            const { rows: normalized, adjustments } = normalizeTables(validRows, gamesPerTeam);
            const normalizedById = {};
            normalized.forEach(r => { normalizedById[r.club_id] = r; });

            const finalRows = tableRows.map(row => {
                if (!row.club_id || !normalizedById[row.club_id]) return row;
                const nr = normalizedById[row.club_id];
                return {
                    ...row,
                    played: nr.played,
                    won: nr.won,
                    drawn: nr.drawn,
                    lost: nr.lost,
                    goals_for: nr.goals_for,
                    goals_against: nr.goals_against,
                    goal_difference: (nr.goals_for || 0) - (nr.goals_against || 0),
                    points: (nr.won || 0) * 3 + (nr.drawn || 0),
                };
            });

            setTableRows(finalRows);
            if (adjustments.length === 0) {
                toast.success('Table was already consistent — no changes needed.');
            } else {
                toast.success(`Normalized table with ${adjustments.length} small adjustments (W/L & goal balance).`);
            }
        } catch (err) {
            console.error('Failed to normalize:', err);
            toast.error(`Failed to normalize: ${err.message || err}`);
        } finally {
            setLoading(false);
        }
    };

    const generateStats = async (forceOverwrite) => {
        if (forceOverwrite && hasStats) {
            if (!window.confirm('This will overwrite the existing stats for all clubs in this table. Continue?')) return;
        }
        setLoading(true);
        try {
            const knownData = tableRows
                .filter(r => r.club_name)
                .map((r, idx) => `${idx + 1}. ${r.club_name}${r.points > 0 ? ` (${r.points} pts)` : ''}${r.goals_for > 0 ? ` GF:${r.goals_for}` : ''}`)
                .join('\n');

            // Weighted season flavour — mostly normal/close; "chaotic" is rare so freak
            // scorelines don't dominate the generated history.
            const flavourRoll = Math.random();
            const seasonType = flavourRoll < 0.55 ? 'normal'
                : flavourRoll < 0.80 ? 'close'
                : flavourRoll < 0.95 ? 'dominant'
                : 'chaotic';

            const totalLeagueGames = (numTeams * gamesPerTeam) / 2;
            // League-wide goals-per-game sits in a realistic ~2.5-2.9 band.
            const leagueGpg = (2.5 + Math.random() * 0.4).toFixed(2);
            const totalLeagueGoals = Math.round(totalLeagueGames * leagueGpg);
            // Average goals a single team scores across the season.
            const avgTeamGoals = (totalLeagueGoals / numTeams).toFixed(0);

            const prompt = `Generate REALISTIC football league table statistics for a ${numTeams}-team league. Model this on real-world domestic leagues (think typical European top/second flights — NOT arcade or fantasy football).

LEAGUE: ${league?.name || 'Football League'} (Tier ${league?.tier || 1})
SEASON: ${seasonData?.year || 'Current'}
GAMES PER TEAM: ${gamesPerTeam}
TEAMS: ${numTeams}
TOTAL LEAGUE MATCHES: ${totalLeagueGames}
TARGET LEAGUE GOALS-PER-GAME: ~${leagueGpg} (so total goals scored across ALL teams ≈ ${totalLeagueGoals})
AVERAGE GOALS PER TEAM (season): ~${avgTeamGoals}

SEASON FLAVOUR: ${seasonType.toUpperCase()}
${seasonType === 'close' ? '- Tight title race: top 2-3 within 3-6 points. Relegation scrap also tight.' : ''}
${seasonType === 'dominant' ? '- Champion is strong (wins by ~8-12 pts). The rest of the table is normal.' : ''}
${seasonType === 'chaotic' ? '- Slightly unusual ordering, but STILL realistic numbers — no arcade scorelines.' : ''}
${seasonType === 'normal' ? '- Standard realistic season: 2-4 points between adjacent positions.' : ''}

TEAMS IN FINAL ORDER (1st to last):
${knownData}

HARD REALISM RULES — follow exactly:
1. W + D + L = ${gamesPerTeam} for EVERY team.
2. Points = W*3 + D. GD = GF - GA.
3. Sum of all W across the league = sum of all L (every win has a loss).
4. Sum of all GF across the league = sum of all GA = ${totalLeagueGoals}.
5. WIN/DRAW/LOSS distribution (per team, for ${gamesPerTeam} games):
   - Top team: ~${Math.round(gamesPerTeam*0.6)}-${Math.round(gamesPerTeam*0.75)} wins, ~${Math.round(gamesPerTeam*0.15)} draws, rest losses.
   - Mid-table: ~${Math.round(gamesPerTeam*0.4)}-${Math.round(gamesPerTeam*0.5)} wins.
   - Relegated teams: ~${Math.round(gamesPerTeam*0.15)}-${Math.round(gamesPerTeam*0.3)} wins, ${Math.round(gamesPerTeam*0.2)}-${Math.round(gamesPerTeam*0.35)} draws — they still WIN GAMES. NO team should have 0, 1, or 2 wins.
   - A healthy spread of draws (5-12 per team) — not everyone wins/loses.
6. GOALS (per team, across the WHOLE season of ${gamesPerTeam} games):
   - Average team scores ~${avgTeamGoals} goals.
   - Top scorer: ${Math.round(gamesPerTeam*1.5)}-${Math.round(gamesPerTeam*1.9)} goals. NO team above ${Math.round(gamesPerTeam*2.0)}.
   - Weakest attack: ${Math.round(gamesPerTeam*0.7)}-${Math.round(gamesPerTeam*0.9)} goals. NO team below ${Math.round(gamesPerTeam*0.55)}.
   - Defense (GA) ranges similarly; a tight defense concedes ~${Math.round(gamesPerTeam*0.8)}-${Math.round(gamesPerTeam*1.1)}, a leaky one ~${Math.round(gamesPerTeam*1.4)}-${Math.round(gamesPerTeam*1.8)}. NO team above ${Math.round(gamesPerTeam*2.0)} conceded.
   - Goals-per-game per team should average 0.9-1.6. Think 1-2 goals a match, NOT 4-5.
7. Keep it believable: a 2nd-place team may have a better GD than the champion; a mid-table side can be the top scorers; a relegated team may outscore one above it. But the NUMBERS stay in the bands above.

Return realistic stats. No outlier scoreline inflation.`;

            const result = await base44.integrations.Core.InvokeLLM({
                prompt,
                response_json_schema: {
                    type: "object",
                    properties: {
                        teams: {
                            type: "array",
                            items: {
                                type: "object",
                                properties: {
                                    position: { type: "number" },
                                    played: { type: "number" },
                                    won: { type: "number" },
                                    drawn: { type: "number" },
                                    lost: { type: "number" },
                                    goals_for: { type: "number" },
                                    goals_against: { type: "number" },
                                    points: { type: "number" }
                                }
                            }
                        }
                    }
                }
            });

            if (result.teams && result.teams.length > 0) {
                // Apply AI stats — force overwrite when regenerating, fill only empties otherwise
                const withStats = tableRows.map((row, idx) => {
                    if (!row.club_name) return row;
                    const aiStats = result.teams.find(t => t.position === idx + 1) || result.teams[idx];
                    if (!aiStats) return row;

                    if (forceOverwrite) {
                        return {
                            ...row,
                            played: aiStats.played || gamesPerTeam,
                            won: aiStats.won || 0,
                            drawn: aiStats.drawn || 0,
                            lost: aiStats.lost || 0,
                            goals_for: aiStats.goals_for || 0,
                            goals_against: aiStats.goals_against || 0,
                        };
                    }
                    return {
                        ...row,
                        played: row.played || aiStats.played || gamesPerTeam,
                        won: row.won || aiStats.won || 0,
                        drawn: row.drawn || aiStats.drawn || 0,
                        lost: row.lost || aiStats.lost || 0,
                        goals_for: row.goals_for || aiStats.goals_for || 0,
                        goals_against: row.goals_against || aiStats.goals_against || 0,
                    };
                });

                // Normalize so the table is mathematically consistent — this is what lets
                // the deterministic backfiller reproduce the exact W/D/L and goals.
                const validRows = withStats.filter(r => r.club_name && r.club_id);
                const { rows: normalized, adjustments } = normalizeTables(validRows, gamesPerTeam);
                const normalizedById = {};
                normalized.forEach(r => { normalizedById[r.club_id] = r; });

                const finalRows = withStats.map(row => {
                    if (!row.club_id || !normalizedById[row.club_id]) return row;
                    const nr = normalizedById[row.club_id];
                    return {
                        ...row,
                        played: nr.played,
                        won: nr.won,
                        drawn: nr.drawn,
                        lost: nr.lost,
                        goals_for: nr.goals_for,
                        goals_against: nr.goals_against,
                        goal_difference: (nr.goals_for || 0) - (nr.goals_against || 0),
                        points: (nr.won || 0) * 3 + (nr.drawn || 0),
                    };
                });

                setTableRows(finalRows);

                const afterCheck = checkConsistency(finalRows.filter(r => r.club_name && r.club_id));
                if (afterCheck.consistent) {
                    toast.success(`Stats generated and normalized — table is now internally consistent (${adjustments.length} adjustments).`);
                } else {
                    toast.warning(`Stats generated with ${adjustments.length} adjustments. Table still has minor imbalances (W/L gap ${afterCheck.wlGap}, GF/GA gap ${afterCheck.gfGaGap}).`);
                }
            }
        } catch (err) {
            console.error('Failed to generate stats:', err);
            toast.error(`Failed to generate stats: ${err.message || err}`);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="flex gap-2 flex-wrap">
            <Button
                onClick={() => generateStats(false)}
                disabled={loading || numTeams < 2}
                variant="outline"
                className="border-purple-300 text-purple-700 hover:bg-purple-50"
            >
                {loading ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
                ) : (
                    <><Wand2 className="w-4 h-4 mr-2" /> AI Generate Stats</>
                )}
            </Button>
            <Button
                onClick={() => generateStats(true)}
                disabled={loading || numTeams < 2}
                variant="outline"
                className="border-amber-300 text-amber-700 hover:bg-amber-50"
            >
                {loading ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Regenerating...</>
                ) : (
                    <><RefreshCw className="w-4 h-4 mr-2" /> Regenerate Stats</>
                )}
            </Button>
            <Button
                onClick={normalizeExisting}
                disabled={loading || numTeams < 2}
                variant="outline"
                className="border-blue-300 text-blue-700 hover:bg-blue-50"
            >
                {loading ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Normalizing...</>
                ) : (
                    <><Sliders className="w-4 h-4 mr-2" /> Normalize Stats</>
                )}
            </Button>
        </div>
    );
}