import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Loader2, Wand2, RefreshCw } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { normalizeTables, checkConsistency } from '@/lib/matchBackfiller';
import { toast } from "sonner";

/**
 * Generates (and regenerates) realistic league table stats via LLM, then
 * normalizes them so W+D+L=played, sum(W)=sum(L), and sum(GF)=sum(GA) —
 * which is what the deterministic backfiller needs to reproduce the table exactly.
 *
 * Match results themselves are generated by <BackfillMatchesButton />, which
 * guarantees a match to the table (the LLM match generator did NOT, so it was removed).
 */
export default function AIStatsGenerator({ tableRows, setTableRows, seasonData, league, divisionTeamCount, seasonId, leagueId }) {
    const [loading, setLoading] = useState(false);

    const numTeams = tableRows.filter(r => r.club_name).length;
    const teamsInDivision = divisionTeamCount || numTeams;
    const gamesPerTeam = (teamsInDivision - 1) * 2;
    const hasStats = tableRows.some(r => (r.won || 0) > 0 || (r.drawn || 0) > 0 || (r.lost || 0) > 0);

    const generateStats = async (forceOverwrite) => {
        if (forceOverwrite && hasStats) {
            if (!window.confirm('This will overwrite the existing stats for all clubs in this table. Continue?')) return;
        }
        setLoading(true);
        try {
            const knownData = tableRows
                .filter(r => r.club_name)
                .map((r, idx) => `${idx + 1}. ${r.club_name}${r.points > 0 ? ` (${r.points} pts)` : ''}${r.goals_for > 0 ? ` GF:${r.goals_for}` : ''}`)
                .join('\n');

            const seasonTypes = ['close', 'dominant', 'chaotic', 'normal'];
            const seasonType = seasonTypes[Math.floor(Math.random() * seasonTypes.length)];

            const prompt = `Generate realistic and VARIED football league table statistics for a ${numTeams}-team league season.

LEAGUE: ${league?.name || 'Football League'} (Tier ${league?.tier || 1})
SEASON: ${seasonData?.year || 'Current'}
GAMES PER TEAM: ${gamesPerTeam}

SEASON TYPE: ${seasonType.toUpperCase()}
${seasonType === 'close' ? '- This was a TIGHT title race! Top 2-3 teams within 3-5 points. Relegation battle also close.' : ''}
${seasonType === 'dominant' ? '- Champion was DOMINANT! Won by 10-15+ points. Mid-table competitive.' : ''}
${seasonType === 'chaotic' ? '- UNPREDICTABLE season! Surprise results, unusual stats, maybe high-scoring team mid-table.' : ''}
${seasonType === 'normal' ? '- Standard season with realistic gaps (2-4 points between positions).' : ''}

TEAMS IN ORDER (1st to last):
${knownData}

CRITICAL REQUIREMENTS:
1. W + D + L MUST equal exactly ${gamesPerTeam} for every team
2. Points = (W × 3) + D - calculate correctly!
3. GD = GF - GA
4. The TOTAL wins across all teams MUST equal the TOTAL losses (every win has a corresponding loss)
5. The TOTAL goals scored across all teams MUST equal the TOTAL goals conceded
6. Add REALISTIC VARIETY:
   - Some defensive teams (low GF, low GA)
   - Some attacking but leaky (high GF, high GA)
   - Some draw specialists
   - Bottom teams still score 30-50 goals
7. Create interesting storylines:
   - Maybe 2nd has better GD but fewer points
   - A high-scoring team finishes 4th-6th
   - Relegated team might outscore team above them

Generate UNIQUE stats - not linear progression!`;

            const result = await base44.integrations.Core.InvokeLLM({
                prompt,
                response_json_schema: {
                    type: "object",
                    properties: {
                        teams: {
                            type: "array",
                            items: {
                                type: "object",
                                properties: {
                                    position: { type: "number" },
                                    played: { type: "number" },
                                    won: { type: "number" },
                                    drawn: { type: "number" },
                                    lost: { type: "number" },
                                    goals_for: { type: "number" },
                                    goals_against: { type: "number" },
                                    points: { type: "number" }
                                }
                            }
                        }
                    }
                }
            });

            if (result.teams && result.teams.length > 0) {
                // Apply AI stats — force overwrite when regenerating, fill only empties otherwise
                const withStats = tableRows.map((row, idx) => {
                    if (!row.club_name) return row;
                    const aiStats = result.teams.find(t => t.position === idx + 1) || result.teams[idx];
                    if (!aiStats) return row;

                    if (forceOverwrite) {
                        return {
                            ...row,
                            played: aiStats.played || gamesPerTeam,
                            won: aiStats.won || 0,
                            drawn: aiStats.drawn || 0,
                            lost: aiStats.lost || 0,
                            goals_for: aiStats.goals_for || 0,
                            goals_against: aiStats.goals_against || 0,
                        };
                    }
                    return {
                        ...row,
                        played: row.played || aiStats.played || gamesPerTeam,
                        won: row.won || aiStats.won || 0,
                        drawn: row.drawn || aiStats.drawn || 0,
                        lost: row.lost || aiStats.lost || 0,
                        goals_for: row.goals_for || aiStats.goals_for || 0,
                        goals_against: row.goals_against || aiStats.goals_against || 0,
                    };
                });

                // Normalize so the table is mathematically consistent — this is what lets
                // the deterministic backfiller reproduce the exact W/D/L and goals.
                const validRows = withStats.filter(r => r.club_name && r.club_id);
                const { rows: normalized, adjustments } = normalizeTables(validRows, gamesPerTeam);
                const normalizedById = {};
                normalized.forEach(r => { normalizedById[r.club_id] = r; });

                const finalRows = withStats.map(row => {
                    if (!row.club_id || !normalizedById[row.club_id]) return row;
                    const nr = normalizedById[row.club_id];
                    return {
                        ...row,
                        played: nr.played,
                        won: nr.won,
                        drawn: nr.drawn,
                        lost: nr.lost,
                        goals_for: nr.goals_for,
                        goals_against: nr.goals_against,
                        goal_difference: (nr.goals_for || 0) - (nr.goals_against || 0),
                        points: (nr.won || 0) * 3 + (nr.drawn || 0),
                    };
                });

                setTableRows(finalRows);

                const afterCheck = checkConsistency(finalRows.filter(r => r.club_name && r.club_id));
                if (afterCheck.consistent) {
                    toast.success(`Stats generated and normalized — table is now internally consistent (${adjustments.length} adjustments).`);
                } else {
                    toast.warning(`Stats generated with ${adjustments.length} adjustments. Table still has minor imbalances (W/L gap ${afterCheck.wlGap}, GF/GA gap ${afterCheck.gfGaGap}).`);
                }
            }
        } catch (err) {
            console.error('Failed to generate stats:', err);
            toast.error(`Failed to generate stats: ${err.message || err}`);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="flex gap-2 flex-wrap">
            <Button
                onClick={() => generateStats(false)}
                disabled={loading || numTeams < 2}
                variant="outline"
                className="border-purple-300 text-purple-700 hover:bg-purple-50"
            >
                {loading ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
                ) : (
                    <><Wand2 className="w-4 h-4 mr-2" /> AI Generate Stats</>
                )}
            </Button>
            <Button
                onClick={() => generateStats(true)}
                disabled={loading || numTeams < 2}
                variant="outline"
                className="border-amber-300 text-amber-700 hover:bg-amber-50"
            >
                {loading ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Regenerating...</>
                ) : (
                    <><RefreshCw className="w-4 h-4 mr-2" /> Regenerate Stats</>
                )}
            </Button>
        </div>
    );
}